import { Word } from '../types';

const vocabularyList: Word[] = [
  { vietnamese: 'bắt đầu', english: 'begin' },
  { vietnamese: 'ba lô cỡ lớn', english: 'rucksack' },
  { vietnamese: 'cuộc thi', english: 'competition' },
  { vietnamese: 'tham gia', english: 'join' },
  { vietnamese: 'một số', english: 'several' },
  { vietnamese: 'tiêu (tiền), dùng (thời gian)', english: 'spend' },
  { vietnamese: 'ngôn ngữ', english: 'language' },
  { vietnamese: 'kính râm', english: 'sunglasses' },
  { vietnamese: 'đắt', english: 'expensive' },
  { vietnamese: 'dễ thương', english: 'lovely' },
  { vietnamese: 'điện thoại', english: 'telephone' },
  { vietnamese: 'lá cờ', english: 'flag' },
  { vietnamese: 'gặp gỡ', english: 'meet' },
  { vietnamese: 'thời gian biểu', english: 'timetable' },
  { vietnamese: 'cùng nhau', english: 'together' },
  { vietnamese: 'nhóm', english: 'group' },
  { vietnamese: 'tháng', english: 'month' },
  { vietnamese: 'ngày mai', english: 'tomorrow' },
  { vietnamese: 'đoán', english: 'guess' },
  { vietnamese: 'vòng cổ', english: 'necklace' },
  { vietnamese: 'tuyệt vời', english: 'wonderful' },
  { vietnamese: 'mùa thu', english: 'autumn' },
  { vietnamese: 'mật ong', english: 'honey' },
  { vietnamese: 'nhàm chán', english: 'bored' },
  { vietnamese: 'mứt', english: 'jam' },
  { vietnamese: 'đốt', english: 'burn' },
  { vietnamese: 'sau đó', english: 'later' },
  { vietnamese: 'nhà hóa học', english: 'chemist' },
  { vietnamese: 'bữa ăn', english: 'meal' },
  { vietnamese: 'buổi hòa nhạc', english: 'concert' },
  { vietnamese: 'thuốc', english: 'medicine' },
  { vietnamese: 'cuộc đối thoại', english: 'conversation' },
  { vietnamese: 'cộng sự', english: 'partner' },
  { vietnamese: 'cắt', english: 'cut' },
  { vietnamese: 'hạt tiêu', english: 'pepper' },
  { vietnamese: 'quyết định', english: 'decide' },
  { vietnamese: 'mảnh, phần', english: 'piece' },
  { vietnamese: 'cái trống', english: 'drum' },
  { vietnamese: 'pizza', english: 'pizza' },
  { vietnamese: 'lẫn nhau, nhau', english: 'each other' },
  { vietnamese: 'chuẩn bị', english: 'prepare' },
  { vietnamese: 'ngã', english: 'fall over' },
  { vietnamese: 'muối', english: 'salt' },
  { vietnamese: 'bột', english: 'flour' },
  { vietnamese: 'ca sĩ', english: 'singer' },
  { vietnamese: 'tủ lạnh', english: 'fridge' },
  { vietnamese: 'mùa xuân', english: 'spring' },
  { vietnamese: 'diễn viên', english: 'actor' },
  { vietnamese: 'báo', english: 'newspaper' },
  { vietnamese: 'nghệ sĩ', english: 'artist' },
  { vietnamese: 'bạch tuộc', english: 'octopus' },
  { vietnamese: 'nhiếp ảnh gia', english: 'photographer' },
  { vietnamese: 'vương miện', english: 'crown' },
  { vietnamese: 'hoàng hậu', english: 'queen' },
  { vietnamese: 'sẵn sàng', english: 'ready' },
  { vietnamese: 'thích thú, hào hứng', english: 'excited' },
  { vietnamese: 'dụng cụ', english: 'instruments' },
  { vietnamese: 'sân khấu', english: 'stage' },
  { vietnamese: 'nhà báo', english: 'journalist' },
  { vietnamese: 'nhà hát', english: 'theater' },
  { vietnamese: 'nhà vua', english: 'king' },
  { vietnamese: 'đàn vi-ô-lông', english: 'violin' },
  { vietnamese: 'lịch', english: 'calendar' },
  { vietnamese: 'thích hơn', english: 'prefer' },
  { vietnamese: 'phim hoạt hình', english: 'cartoon' },
  { vietnamese: 'chương trình', english: 'programme' },
  { vietnamese: 'kênh', english: 'channel' },
  { vietnamese: 'nên', english: 'should' },
  { vietnamese: 'cờ vua', english: 'chess' },
  { vietnamese: 'trượt tuyết', english: 'ski' },
  { vietnamese: 'trong suốt (khoảng thời gian)', english: 'during' },
  { vietnamese: 'trượt tuyết (môn thể thao)', english: 'skiing' },
  { vietnamese: 'đói', english: 'hungry' },
  { vietnamese: 'quả cầu tuyết', english: 'snowball' },
  { vietnamese: 'nếu', english: 'if' },
  { vietnamese: 'trượt ván trên tuyết', english: 'snowboarding' },
  { vietnamese: 'tử tế, tốt bụng', english: 'kind' },
  { vietnamese: 'người tuyết', english: 'snowman' },
  { vietnamese: 'tạp chí', english: 'magazine' },
  { vietnamese: 'ở', english: 'stay' },
  { vietnamese: 'kết hôn', english: 'married' },
  { vietnamese: 'mùa đông', english: 'winter' },
  { vietnamese: 'phổ biến', english: 'popular' },
  { vietnamese: 'bánh quy', english: 'biscuit' },
  { vietnamese: 'rời khỏi', english: 'leave' },
  { vietnamese: 'bơ', english: 'butter' },
  { vietnamese: 'một chút', english: 'little' },
  { vietnamese: 'chiếc đũa', english: 'chopstick' },
  { vietnamese: 'may mắn', english: 'lucky' },
  { vietnamese: 'ngon', english: 'delicious' },
  { vietnamese: 'nhà hàng', english: 'restaurant' },
  { vietnamese: 'bao giờ', english: 'ever' },
  { vietnamese: 'đặc biệt', english: 'special' },
  { vietnamese: 'mọi nơi', english: 'everywhere' },
  { vietnamese: 'cái thìa', english: 'spoon' },
  { vietnamese: 'cảm thấy', english: 'feel' },
  { vietnamese: 'đường', english: 'sugar' },
  { vietnamese: 'cái nĩa', english: 'fork' },
  { vietnamese: 'chắc chắn', english: 'sure' },
  { vietnamese: 'vui vẻ', english: 'fun' },
  { vietnamese: 'qua', english: 'through' },
  { vietnamese: 'quan trọng', english: 'important' },
  { vietnamese: 'thời gian', english: 'time' },
  { vietnamese: 'cái dao', english: 'knife' },
  { vietnamese: 'người bồi bàn', english: 'waiter' },
  { vietnamese: 'đã', english: 'already' },
  { vietnamese: 'nhìn', english: 'look' },
  { vietnamese: 'cây cầu', english: 'bridge' },
  { vietnamese: 'kim loại', english: 'metal' },
  { vietnamese: 'bươm bướm', english: 'butterfly' },
  { vietnamese: 'tổ (chim), ổ (chuột)', english: 'nest' },
  { vietnamese: 'khác', english: 'else' },
  { vietnamese: 'nhựa', english: 'plastic' },
  { vietnamese: 'môi trường', english: 'environment' },
  { vietnamese: 'âm thanh', english: 'sound' },
  { vietnamese: 'cái cổng', english: 'gate' },
  { vietnamese: 'thủy tinh', english: 'glass' },
  { vietnamese: 'thiên nga', english: 'swan' },
  { vietnamese: 'côn trùng', english: 'insect' },
  { vietnamese: 'thường xuyên', english: 'usually' },
  { vietnamese: 'bức thư', english: 'letter' },
  { vietnamese: 'cánh', english: 'wing' },
  { vietnamese: 'thích', english: 'like' },
  { vietnamese: 'gỗ', english: 'wood' },
  { vietnamese: 'sân bay', english: 'airport' },
  { vietnamese: 'phía Bắc', english: 'north' },
  { vietnamese: 'ba lô', english: 'backpack' },
  { vietnamese: 'không nơi đâu', english: 'nowhere' },
  { vietnamese: 'trại', english: 'camp' },
  { vietnamese: 'hành khách', english: 'passenger' },
  { vietnamese: 'lâu đài', english: 'castle' },
  { vietnamese: 'Kim tự tháp', english: 'pyramid' },
  { vietnamese: 'hang động', english: 'cave' },
  { vietnamese: 'đường sắt', english: 'railway' },
  { vietnamese: 'tối tăm', english: 'dark' },
  { vietnamese: 'phía Nam', english: 'south' },
  { vietnamese: 'sa mạc', english: 'desert' },
  { vietnamese: 'vali', english: 'suitcase' },
  { vietnamese: 'phía Đông', english: 'east' },
  { vietnamese: 'cái lều', english: 'tent' },
  { vietnamese: 'xa', english: 'far' },
  { vietnamese: 'giao thông', english: 'traffic' },
  { vietnamese: 'nhanh', english: 'fast' },
  { vietnamese: 'không vui', english: 'unhappy' },
  { vietnamese: 'khách sạn', english: 'hotel' },
  { vietnamese: 'ghé thăm', english: 'visit' },
  { vietnamese: 'ánh sáng', english: 'light' },
  { vietnamese: 'phía Tây', english: 'west' },
  { vietnamese: 'bảo tàng', english: 'museum' },
  { vietnamese: 'phi hành gia', english: 'astronaut' },
  { vietnamese: 'cảnh sát', english: 'police officers' },
  { vietnamese: 'kỹ sư', english: 'engineer' },
  { vietnamese: 'đồn cảnh sát', english: 'police station' },
  { vietnamese: 'phong thư', english: 'envelope' },
  { vietnamese: 'bưu thiếp', english: 'postcard' },
  { vietnamese: 'nhà máy', english: 'factory' },
  { vietnamese: 'tên lửa', english: 'rocket' },
  { vietnamese: 'lính cứu hỏa', english: 'firefighter' },
  { vietnamese: 'thư ký', english: 'secretary' },
  { vietnamese: 'trạm cứu hỏa', english: 'fire station' },
  { vietnamese: 'không gian', english: 'space' },
  { vietnamese: 'nghề nghiệp', english: 'job' },
  { vietnamese: 'con tem', english: 'stamp' },
  { vietnamese: 'thợ cơ khí', english: 'mechanic' },
  { vietnamese: 'mùa hè', english: 'summer' },
  { vietnamese: 'phi công', english: 'pilot' },
  { vietnamese: 'một nghìn', english: 'a thousand' },
  { vietnamese: 'một triệu', english: 'a million' },
  { vietnamese: 'một trăm', english: 'a hundred' },
  { vietnamese: 'số không', english: 'zero' },
  { vietnamese: 'bất kỳ điều gì', english: 'anything' },
  { vietnamese: 'bao lâu', english: 'how long' },
  { vietnamese: 'đến', english: 'arrive' },
  { vietnamese: 'thông tin', english: 'information' },
  { vietnamese: 'vỡ', english: 'broken' },
  { vietnamese: 'chỉ', english: 'just' },
  { vietnamese: 'muộn, trễ', english: 'late' },
  { vietnamese: 'sớm', english: 'early' },
  { vietnamese: 'ở giữa', english: 'middle' },
  { vietnamese: 'đủ', english: 'enough' },
  { vietnamese: 'bài thi', english: 'exam' },
  { vietnamese: 'vấn đề', english: 'problem' },
  { vietnamese: 'quên', english: 'forget' },
  { vietnamese: 'cái kệ', english: 'shelf' },
  { vietnamese: 'thân thiện', english: 'friendly' },
  { vietnamese: 'đằng trước', english: 'front' },
  { vietnamese: 'tắt', english: 'turn off' },
  { vietnamese: 'khó', english: 'hard' },
  { vietnamese: 'bật', english: 'turn on' },
  { vietnamese: 'không có', english: 'without' },
  { vietnamese: 'lo lắng', english: 'worried' },
];

const shuffleArray = <T,>(array: T[]): T[] => {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};

const chunkArray = <T,>(array: T[], size: number): T[][] => {
  const chunkedArr = [];
  let index = 0;
  while (index < array.length) {
    chunkedArr.push(array.slice(index, size + index));
    index += size;
  }
  return chunkedArr;
};

const fullVocabulary = shuffleArray(vocabularyList);
const wordsPerPage = 10;
export const vocabularyPages: Word[][] = chunkArray(fullVocabulary, wordsPerPage);